<?php

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function mp3player_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.mp3player':
      return '<p>'. t("A module to integrate the WordPress Audio Player into Drupal.") .'</p>';
  }
}

/**
 * Implements hook_page_attachments().
 */
function mp3player_page_attachments(array &$attachments) {

  $attachments['#attached']['library'][] = 'mp3player/mp3player_js';

}
